### ISSUE TITLE
0.08版启动闪退

### ISSUE THREAD

**Issue by carterbranigan** [SWHL/RapidVideOCRDesktop#4]
执行RapidVideOCR.exe闪退，使用命令行执行，报错信息如下，谢谢。
Traceback (most recent call last):
  File "RapidVideOCR.py", line 24, in <module>
ModuleNotFoundError: No module named 'rapid_videocr'
[14704] Failed to execute script 'RapidVideOCR' due to unhandled exception!

**Comment by SWHL** [comment]
从信息来看是没有安装rapid_videocr，可以通过以下命令安装使用：
```bash
$ pip install rapid_videocr
```
使用教程，参见：[link](https://swhl.github.io/RapidVideOCR/docs/tutorial/senior/)

**Comment by carterbranigan** [comment]
我使用的是界面版，exe文件，还需要pip安装 rapid_videocr么？按照https://swhl.github.io/RapidVideOCR/docs/tutorial/beginner/这个操作的，但是双击exe文件就报了上面的错误。

**Comment by SWHL** [comment]
由于我手头没有Windows设备，不能测试是否可用。我重新编译发布了一个新版，有空的话，你那里再试试呗

**Comment by carterbranigan** [comment]
谢谢，0.0.9版可以打开使用了，我试了一个文件，完整视频成功。只是，OCR的质量好像不太高，每十句话里可能得有两三句识别有错字，有的连着多个字都是错的。不过还是非常感谢，使用起来挺方便，速度也很快，要是质量能在高一些就更好了。

**Comment by SWHL** [comment]
后期会逐步提升的，欢迎持续关注
