### ISSUE TITLE
Bug: English Windows release is actually Chinese

### ISSUE THREAD

**Issue by Brycey92** [SWHL/RapidVideOCRDesktop#7]
请提供下述完整信息以便快速定位问题
(Please provide the following information to quickly locate the problem)
- **系统环境/System Environment**: Windows 10
- **使用的是哪门语言的程序/Which programing language**:
- **所使用语言相关版本信息/Version**: 0.0.9
- **OnnxRuntime版本/OnnxRuntime Version**:
- **使用当前软件/库的版本/Use version**:
- **可复现问题的demo和文件/Demo of reproducible problems**:
- **完整报错/Complete Error Message**:
- **可能的解决方案/Possible solutions**:

**Comment by SWHL** [comment]
This problem has been solved, and this is the latest download [link](https://github.com/SWHL/RapidVideOCRDesktop/releases/tag/v0.0.10).

Please try again.

**Comment by Voxy96** [comment]
I would like to know if it is possible to make RapidVideo use Video Subfinder with the GPU. And if it is possible, how can I do this?
I appreciate your dedication in bringing such a spectacular program! 😁
